version: '3.8'

services:
  auth_service_db:
    image: postgres:15
    container_name: auth_service_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: auth_db
      POSTGRES_USER: auth_service_user
      POSTGRES_PASSWORD: qwertyui
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
     test: ["CMD-SHELL", "pg_isready -U auth_service_user -d auth_db"]
     interval: 5s
     timeout: 5s
     retries: 5
    ports:
      - '7500:5432'

  auth-service:
    image: auth_service:latest
    depends_on:
      auth_service_db:
        condition: service_healthy
    ports:
      - '8080:8080'
      - '9090:9090'
    volumes:
      - ./Config.toml:/app/Config.toml
      - ./logs:/app/logs
      - ./public.crt:/home/ballerina/public.crt
      - ./private.key:/home/ballerina/private.key

    environment:
      BAL_CONFIG_FILES: /app/Config.toml


volumes:
  pgdata: